### ISSUE TITLE
Increase the serial limit for RKE2 agents play (or make it configurable)

### ISSUE THREAD

**Issue by aaron-iles** [rancherfederal/rke2-ansible#145]
In [site.yml](https://github.com/rancherfederal/rke2-ansible/blob/main/site.yml) the 'Agent Play' has `serial: 3` set. This makes creating clusters with hundreds or thousands of agents painfully slow (on the order of hours or days). 
Earlier versions of this did not have such a limit on the agents play. Is there a reason such a small limit was set on the agents? Can this number be increased to something more reasonable like 50 or made a variable like 
`serial: "{{ agent_play_limit | default(3) }}"`

**Comment by mddamato** [comment]
@aaron-iles Thank you for the suggestion. This limit was originally imposed due to a bug in an older RKE2 implementation where the ETCD database joining process would hit a race condition if more than one was trying to join the cluster at one time. If this condition lasted long enough the joining process would time-out and the member would be permanently rejected. I believe this problem has since been resolved and we can increase the limit. It will now initialize the first server in the inventory list and do the rest up to 5 at a time and 10 at a time for agents.

see #227
